### Solving XOR problem using Feed Forward Neural Network

In [1]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense

In [2]:
model = Sequential()
model.add(Dense(units=2,activation='relu',input_dim=2))
model.add(Dense(units=1,activation='sigmoid'))

In [3]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics='accuracy')
print(model.summary())
print(model.get_weights())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 2)                 6         
                                                                 
 dense_1 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________
None
[array([[-0.7195465, -0.616876 ],
       [ 1.0088433, -1.0099027]], dtype=float32), array([0., 0.], dtype=float32), array([[ 0.15790236],
       [-1.2449576 ]], dtype=float32), array([0.], dtype=float32)]


In [4]:
x = np.array([[0.,0,],[0.,1.],[1.,0.,],[1.,1.]])
print(x)

[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]


In [5]:
y = np.array([0.,1.,1.,0.])
print(y)

[0. 1. 1. 0.]


In [6]:
model.fit(x,y,epochs=200,batch_size=4)

Epoch 1/200
1/1 [==============================] - 0s 345ms/step - loss: 0.6798 - accuracy: 0.5000
Epoch 2/200
1/1 [==============================] - 0s 4ms/step - loss: 0.6797 - accuracy: 0.5000
Epoch 3/200
1/1 [==============================] - 0s 3ms/step - loss: 0.6796 - accuracy: 0.5000
Epoch 4/200
1/1 [==============================] - 0s 4ms/step - loss: 0.6795 - accuracy: 0.5000
Epoch 5/200
1/1 [==============================] - 0s 3ms/step - loss: 0.6793 - accuracy: 0.5000
Epoch 6/200
1/1 [==============================] - 0s 3ms/step - loss: 0.6792 - accuracy: 0.5000
Epoch 7/200
1/1 [==============================] - 0s 3ms/step - loss: 0.6791 - accuracy: 0.5000
Epoch 8/200
1/1 [==============================] - 0s 4ms/step - loss: 0.6790 - accuracy: 0.5000
Epoch 9/200
1/1 [==============================] - 0s 3ms/step - loss: 0.6789 - accuracy: 0.5000
Epoch 10/200
1/1 [==============================] - 0s 3ms/step - loss: 0.6788 - accuracy: 0.5000
Epoch 11/200
1/1 [=========

1/1 [==============================] - 0s 3ms/step - loss: 0.6696 - accuracy: 0.7500
Epoch 85/200
1/1 [==============================] - 0s 4ms/step - loss: 0.6694 - accuracy: 0.7500
Epoch 86/200
1/1 [==============================] - 0s 3ms/step - loss: 0.6693 - accuracy: 0.7500
Epoch 87/200
1/1 [==============================] - 0s 3ms/step - loss: 0.6692 - accuracy: 0.7500
Epoch 88/200
1/1 [==============================] - 0s 3ms/step - loss: 0.6690 - accuracy: 0.7500
Epoch 89/200
1/1 [==============================] - 0s 3ms/step - loss: 0.6689 - accuracy: 0.7500
Epoch 90/200
1/1 [==============================] - 0s 3ms/step - loss: 0.6688 - accuracy: 0.7500
Epoch 91/200
1/1 [==============================] - 0s 3ms/step - loss: 0.6686 - accuracy: 0.7500
Epoch 92/200
1/1 [==============================] - 0s 2ms/step - loss: 0.6685 - accuracy: 0.7500
Epoch 93/200
1/1 [==============================] - 0s 3ms/step - loss: 0.6683 - accuracy: 0.7500
Epoch 94/200
1/1 [===============

1/1 [==============================] - 0s 4ms/step - loss: 0.6581 - accuracy: 0.7500
Epoch 168/200
1/1 [==============================] - 0s 3ms/step - loss: 0.6579 - accuracy: 0.7500
Epoch 169/200
1/1 [==============================] - 0s 2ms/step - loss: 0.6578 - accuracy: 0.7500
Epoch 170/200
1/1 [==============================] - 0s 2ms/step - loss: 0.6576 - accuracy: 0.7500
Epoch 171/200
1/1 [==============================] - 0s 4ms/step - loss: 0.6575 - accuracy: 0.7500
Epoch 172/200
1/1 [==============================] - 0s 2ms/step - loss: 0.6574 - accuracy: 0.7500
Epoch 173/200
1/1 [==============================] - 0s 3ms/step - loss: 0.6572 - accuracy: 0.7500
Epoch 174/200
1/1 [==============================] - 0s 3ms/step - loss: 0.6571 - accuracy: 0.7500
Epoch 175/200
1/1 [==============================] - 0s 4ms/step - loss: 0.6569 - accuracy: 0.7500
Epoch 176/200
1/1 [==============================] - 0s 3ms/step - loss: 0.6568 - accuracy: 0.7500
Epoch 177/200
1/1 [=====

In [7]:
print(model.get_weights())

[array([[-0.9315785, -0.616876 ],
       [ 0.9705609, -1.0099027]], dtype=float32), array([-0.03828222,  0.        ], dtype=float32), array([[ 0.3683044],
       [-1.2449576]], dtype=float32), array([-0.07982057], dtype=float32)]


In [8]:
predictions = model.predict(x)
predictions

1/1 [==============================] - 0s 57ms/step


array([[0.48005545],
       [0.5655067 ],
       [0.48005545],
       [0.48011982]], dtype=float32)

In [9]:
def prob_Bin(list_):
    pred = []
    for i in list_:
        if i>=0.5:
            pred.append(1)
        else:
            pred.append(0)
    return pred

In [10]:
prob_Bin(predictions)

[0, 1, 0, 0]

In [11]:
y

array([0., 1., 1., 0.])

In [12]:
_, accuracy = model.evaluate(x, y)
print(f"Accuracy: {accuracy * 100:.2f}%")

1/1 [==============================] - 0s 97ms/step - loss: 0.6530 - accuracy: 0.7500
Accuracy: 75.00%
