# CREATING MATRICES OF DIFFERENT SHAPES USING CONSTANT VALUES WITH THE HELP OF tensorflow library.

In [1]:
import tensorflow as tf
import keras as kr

In [2]:
X=tf.constant([1,2,3,4,5,6],shape=[3,2])
X

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]])>

In [3]:
Y=tf.constant([1,2,3,4,5,6],shape=[2,3])
Y

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

**Create a 4 by 4 squre matrix A with constant values from 1 to 16.**

In [4]:
A=tf.constant([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16],shape=[4,4])
A

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])>

**Demonstrate matrix multiplication with the help of function of tensorflow library.**

In [5]:
Z=tf.matmul(X,Y) # for standard matrix multiplication
Z

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])>

In [6]:
P=tf.constant([1,2,3,4,5,6],shape=[2,3])
P

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [7]:
Q=tf.constant([7,8,9,10,11,12],shape=[3,2])
Q

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 9, 10],
       [11, 12]])>

In [8]:
R=tf.matmul(P,Q)
R

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]])>

**With the help of tensorflow functions create matrix using random values.**

1. Shape 
2. Range
3. Datatype
4. Datatype of the elements

In [9]:
A=tf.random.uniform([2,2],minval=3,maxval=10,dtype=tf.int32)
A

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[9, 5],
       [7, 4]])>

In [10]:
B=tf.random.uniform([3,3],minval=3,maxval=10,dtype=tf.float32)
B

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[8.800495 , 6.6583557, 6.43443  ],
       [3.4968054, 3.842259 , 6.156041 ],
       [4.9940786, 8.382814 , 9.561087 ]], dtype=float32)>

**Create a matrix C using random values of float datatype having shape 3 by 2**

In [11]:
C = tf.random.uniform([3,2],minval=3,maxval=10,dtype=tf.float32)
C

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[8.568097 , 7.5694914],
       [6.161752 , 5.2997   ],
       [7.6493835, 6.5361166]], dtype=float32)>

In [12]:
eig_value,eig_vec=tf.linalg.eigh(B)
eig_value


<tf.Tensor: shape=(3,), dtype=float32, numpy=array([-2.1558383,  5.209851 , 19.149828 ], dtype=float32)>

In [13]:
eig_vec

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.00700624, -0.86159503,  0.5075479 ],
       [ 0.81185174,  0.30123287,  0.50015527],
       [-0.58382154,  0.40854934,  0.7015979 ]], dtype=float32)>

In [14]:
eig_value,eig_vec=tf.linalg.eigh(X) # Must have float dtype & squre matrix for eigh

InvalidArgumentError: Value for attr 'T' of int32 is not in the list of allowed values: double, float, half, complex64, complex128
	; NodeDef: {{node SelfAdjointEigV2}}; Op<name=SelfAdjointEigV2; signature=input:T -> e:T, v:T; attr=compute_v:bool,default=true; attr=T:type,allowed=[DT_DOUBLE, DT_FLOAT, DT_HALF, DT_COMPLEX64, DT_COMPLEX128]> [Op:SelfAdjointEigV2]