In [1]:
from keras.models import Sequential# supervised
from keras.layers import Dense
import numpy as np

In [2]:
model=Sequential()
model.add(Dense(units=2,input_dim=2,activation='relu')) 
model.add(Dense(units=1,activation='sigmoid'))

In [3]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics='accuracy')
print(model.summary())
print(model.get_weights())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 2)                 6         
                                                                 
 dense_1 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________
None
[array([[-0.6224138 , -0.20656192],
       [-0.18866658,  0.08983707]], dtype=float32), array([0., 0.], dtype=float32), array([[0.9516388 ],
       [0.03395581]], dtype=float32), array([0.], dtype=float32)]


In [4]:
X=np.array([[0.,0.],[0.,1.],[1.,0.],[1.,1.]])
print(X)

[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]


In [5]:
y = np.array([0.,1.,1.,0.])
print(y)

[0. 1. 1. 0.]


In [6]:
model.fit(X,y,epochs=400,batch_size=4)

Epoch 1/400
1/1 [==============================] - 0s 367ms/step - loss: 0.6928 - accuracy: 0.7500
Epoch 2/400
1/1 [==============================] - 0s 5ms/step - loss: 0.6928 - accuracy: 0.7500
Epoch 3/400
1/1 [==============================] - 0s 4ms/step - loss: 0.6927 - accuracy: 0.7500
Epoch 4/400
1/1 [==============================] - 0s 3ms/step - loss: 0.6927 - accuracy: 0.7500
Epoch 5/400
1/1 [==============================] - 0s 4ms/step - loss: 0.6927 - accuracy: 0.7500
Epoch 6/400
1/1 [==============================] - 0s 3ms/step - loss: 0.6927 - accuracy: 0.7500
Epoch 7/400
1/1 [==============================] - 0s 4ms/step - loss: 0.6927 - accuracy: 0.7500
Epoch 8/400
1/1 [==============================] - 0s 3ms/step - loss: 0.6927 - accuracy: 0.7500
Epoch 9/400
1/1 [==============================] - 0s 4ms/step - loss: 0.6926 - accuracy: 0.7500
Epoch 10/400
1/1 [==============================] - 0s 5ms/step - loss: 0.6926 - accuracy: 0.7500
Epoch 11/400
1/1 [=========

1/1 [==============================] - 0s 2ms/step - loss: 0.6902 - accuracy: 0.7500
Epoch 85/400
1/1 [==============================] - 0s 3ms/step - loss: 0.6901 - accuracy: 0.7500
Epoch 86/400
1/1 [==============================] - 0s 3ms/step - loss: 0.6901 - accuracy: 0.7500
Epoch 87/400
1/1 [==============================] - 0s 3ms/step - loss: 0.6900 - accuracy: 0.7500
Epoch 88/400
1/1 [==============================] - 0s 3ms/step - loss: 0.6900 - accuracy: 0.7500
Epoch 89/400
1/1 [==============================] - 0s 4ms/step - loss: 0.6899 - accuracy: 0.7500
Epoch 90/400
1/1 [==============================] - 0s 3ms/step - loss: 0.6899 - accuracy: 0.7500
Epoch 91/400
1/1 [==============================] - 0s 3ms/step - loss: 0.6898 - accuracy: 0.7500
Epoch 92/400
1/1 [==============================] - 0s 2ms/step - loss: 0.6898 - accuracy: 0.7500
Epoch 93/400
1/1 [==============================] - 0s 3ms/step - loss: 0.6897 - accuracy: 0.7500
Epoch 94/400
1/1 [===============

1/1 [==============================] - 0s 3ms/step - loss: 0.6848 - accuracy: 0.7500
Epoch 168/400
1/1 [==============================] - 0s 2ms/step - loss: 0.6848 - accuracy: 0.7500
Epoch 169/400
1/1 [==============================] - 0s 3ms/step - loss: 0.6847 - accuracy: 0.7500
Epoch 170/400
1/1 [==============================] - 0s 3ms/step - loss: 0.6846 - accuracy: 0.7500
Epoch 171/400
1/1 [==============================] - 0s 3ms/step - loss: 0.6845 - accuracy: 0.7500
Epoch 172/400
1/1 [==============================] - 0s 3ms/step - loss: 0.6844 - accuracy: 0.7500
Epoch 173/400
1/1 [==============================] - 0s 2ms/step - loss: 0.6843 - accuracy: 0.7500
Epoch 174/400
1/1 [==============================] - 0s 3ms/step - loss: 0.6843 - accuracy: 0.7500
Epoch 175/400
1/1 [==============================] - 0s 3ms/step - loss: 0.6842 - accuracy: 0.7500
Epoch 176/400
1/1 [==============================] - 0s 3ms/step - loss: 0.6841 - accuracy: 0.7500
Epoch 177/400
1/1 [=====

1/1 [==============================] - 0s 3ms/step - loss: 0.6771 - accuracy: 0.7500
Epoch 250/400
1/1 [==============================] - 0s 3ms/step - loss: 0.6770 - accuracy: 0.7500
Epoch 251/400
1/1 [==============================] - 0s 2ms/step - loss: 0.6769 - accuracy: 0.7500
Epoch 252/400
1/1 [==============================] - 0s 2ms/step - loss: 0.6767 - accuracy: 0.7500
Epoch 253/400
1/1 [==============================] - 0s 3ms/step - loss: 0.6766 - accuracy: 0.7500
Epoch 254/400
1/1 [==============================] - 0s 2ms/step - loss: 0.6765 - accuracy: 0.7500
Epoch 255/400
1/1 [==============================] - 0s 3ms/step - loss: 0.6764 - accuracy: 0.7500
Epoch 256/400
1/1 [==============================] - 0s 3ms/step - loss: 0.6763 - accuracy: 0.7500
Epoch 257/400
1/1 [==============================] - 0s 3ms/step - loss: 0.6762 - accuracy: 0.7500
Epoch 258/400
1/1 [==============================] - 0s 3ms/step - loss: 0.6761 - accuracy: 0.7500
Epoch 259/400
1/1 [=====

1/1 [==============================] - 0s 3ms/step - loss: 0.6671 - accuracy: 0.7500
Epoch 332/400
1/1 [==============================] - 0s 2ms/step - loss: 0.6669 - accuracy: 0.7500
Epoch 333/400
1/1 [==============================] - 0s 3ms/step - loss: 0.6668 - accuracy: 0.7500
Epoch 334/400
1/1 [==============================] - 0s 2ms/step - loss: 0.6666 - accuracy: 0.7500
Epoch 335/400
1/1 [==============================] - 0s 3ms/step - loss: 0.6665 - accuracy: 0.7500
Epoch 336/400
1/1 [==============================] - 0s 3ms/step - loss: 0.6664 - accuracy: 0.7500
Epoch 337/400
1/1 [==============================] - 0s 2ms/step - loss: 0.6662 - accuracy: 0.7500
Epoch 338/400
1/1 [==============================] - 0s 3ms/step - loss: 0.6661 - accuracy: 0.7500
Epoch 339/400
1/1 [==============================] - 0s 3ms/step - loss: 0.6660 - accuracy: 0.7500
Epoch 340/400
1/1 [==============================] - 0s 3ms/step - loss: 0.6658 - accuracy: 0.7500
Epoch 341/400
1/1 [=====

In [7]:
print(model.get_weights())

[array([[-0.6224138 , -0.5416938 ],
       [-0.18866658,  0.5419341 ]], dtype=float32), array([ 0.00000e+00, -9.10237e-05], dtype=float32), array([[0.9516388],
       [0.566283 ]], dtype=float32), array([-0.07633687], dtype=float32)]


In [8]:
y_pred=model.predict(X)
y_pred

1/1 [==============================] - 0s 61ms/step


array([[0.48092505],
       [0.55737114],
       [0.48092505],
       [0.48094615]], dtype=float32)

In [9]:
def prob_Bin(list_):
    pred = []
    for i in list_:
        if i>=0.5:
            pred.append(1)
        else:
            pred.append(0)
    return pred

In [10]:
prob_Bin(y_pred)

[0, 1, 0, 0]

In [11]:
_, accuracy = model.evaluate(X, y)
print(f"Accuracy: {accuracy * 100:.2f}%")

1/1 [==============================] - 0s 99ms/step - loss: 0.6570 - accuracy: 0.7500
Accuracy: 75.00%


# Perform multiclass classification on the wine data set using deep feed forward neural network

In [12]:
from sklearn.datasets import load_wine
import pandas as pd

In [13]:
data= load_wine()
x = pd.DataFrame(data.data,columns = data.feature_names)
y = pd.DataFrame(data.target,columns = ['Target'])
x

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0      14.23        1.71  2.43               15.6      127.0           2.80   
1      13.20        1.78  2.14               11.2      100.0           2.65   
2      13.16        2.36  2.67               18.6      101.0           2.80   
3      14.37        1.95  2.50               16.8      113.0           3.85   
4      13.24        2.59  2.87               21.0      118.0           2.80   
..       ...         ...   ...                ...        ...            ...   
173    13.71        5.65  2.45               20.5       95.0           1.68   
174    13.40        3.91  2.48               23.0      102.0           1.80   
175    13.27        4.28  2.26               20.0      120.0           1.59   
176    13.17        2.59  2.37               20.0      120.0           1.65   
177    14.13        4.10  2.74               24.5       96.0           2.05   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     od280/od315_of_diluted_wines  proline  
0                            3.92   1065.0  
1                            3.40   1050.0  
2                            3.17   1185.0  
3                            3.45   1480.0  
4                            2.93    735.0  
..                            ...      ...  
173                          1.74    740.0  
174                          1.56    750.0  
175                          1.56    835.0  
176                          1.62    840.0  
177                          1.60    560.0  

[178 rows x 13 columns]

In [14]:
y

Target
0         0
1         0
2         0
3         0
4         0
..      ...
173       2
174       2
175       2
176       2
177       2

[178 rows x 1 columns]

In [15]:
from keras.utils import np_utils
encoded_Y=np_utils.to_categorical(y)
encoded_Y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [16]:
model=Sequential()
model.add(Dense(12,input_dim=13,activation='relu')) 
model.add(Dense(8,activation='relu'))
model.add(Dense(3,activation='softmax'))

In [17]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics='accuracy')

In [18]:
model.fit(x,encoded_Y,epochs=100,batch_size=10)

Epoch 1/100
18/18 [==============================] - 0s 959us/step - loss: 69.4608 - accuracy: 0.3315
Epoch 2/100
18/18 [==============================] - 0s 823us/step - loss: 34.4395 - accuracy: 0.3315
Epoch 3/100
18/18 [==============================] - 0s 776us/step - loss: 8.0174 - accuracy: 0.4326
Epoch 4/100
18/18 [==============================] - 0s 720us/step - loss: 3.5974 - accuracy: 0.5281
Epoch 5/100
18/18 [==============================] - 0s 811us/step - loss: 2.2543 - accuracy: 0.4607
Epoch 6/100
18/18 [==============================] - 0s 697us/step - loss: 2.0039 - accuracy: 0.4888
Epoch 7/100
18/18 [==============================] - 0s 706us/step - loss: 1.7878 - accuracy: 0.5225
Epoch 8/100
18/18 [==============================] - 0s 693us/step - loss: 1.6195 - accuracy: 0.5225
Epoch 9/100
18/18 [==============================] - 0s 812us/step - loss: 1.4451 - accuracy: 0.5169
Epoch 10/100
18/18 [==============================] - 0s 785us/step - loss: 1.4153 - accu

18/18 [==============================] - 0s 804us/step - loss: 0.3967 - accuracy: 0.8371
Epoch 82/100
18/18 [==============================] - 0s 868us/step - loss: 0.3778 - accuracy: 0.8764
Epoch 83/100
18/18 [==============================] - 0s 828us/step - loss: 0.4048 - accuracy: 0.8652
Epoch 84/100
18/18 [==============================] - 0s 789us/step - loss: 0.3998 - accuracy: 0.8427
Epoch 85/100
18/18 [==============================] - 0s 762us/step - loss: 0.3560 - accuracy: 0.8876
Epoch 86/100
18/18 [==============================] - 0s 675us/step - loss: 0.4253 - accuracy: 0.8090
Epoch 87/100
18/18 [==============================] - 0s 709us/step - loss: 0.3602 - accuracy: 0.8764
Epoch 88/100
18/18 [==============================] - 0s 751us/step - loss: 0.3761 - accuracy: 0.8596
Epoch 89/100
18/18 [==============================] - 0s 720us/step - loss: 0.3544 - accuracy: 0.8820
Epoch 90/100
18/18 [==============================] - 0s 720us/step - loss: 0.3565 - accuracy: 

In [19]:
predictions=model.predict(x)

6/6 [==============================] - 0s 1ms/step


In [20]:
predictions

array([[8.69940996e-01, 9.57120880e-02, 3.43468674e-02],
       [9.96957064e-01, 2.80379597e-03, 2.39167115e-04],
       [9.99757349e-01, 2.29456433e-04, 1.31833049e-05],
       [9.99995112e-01, 4.74548415e-06, 1.69092459e-07],
       [1.66096762e-01, 6.33420467e-01, 2.00482830e-01],
       [9.99993443e-01, 6.35252309e-06, 2.18068195e-07],
       [9.99985695e-01, 1.39670028e-05, 4.02043128e-07],
       [9.99438345e-01, 5.02761221e-04, 5.88936309e-05],
       [9.97443676e-01, 2.36422266e-03, 1.92163658e-04],
       [9.94073093e-01, 5.01321210e-03, 9.13649623e-04],
       [9.99999642e-01, 3.66262299e-07, 3.05190895e-09],
       [9.99986053e-01, 1.36261424e-05, 3.91705044e-07],
       [9.99997258e-01, 2.71296221e-06, 4.79851643e-08],
       [9.99907613e-01, 9.03811670e-05, 2.05169454e-06],
       [9.99999762e-01, 2.25713094e-07, 3.01226000e-09],
       [9.99738395e-01, 2.21891765e-04, 3.96687392e-05],
       [9.99190867e-01, 7.07397121e-04, 1.01746678e-04],
       [9.89643097e-01, 8.29920

In [21]:
def vec2scalar(list_):
    pred = []
    for i in list_:
        val = [round(j,0) for j in i]
        if val[0]==1.0:
            pred.append(0)
        elif val[1]==1.0:
            pred.append(1)
        else:
            pred.append(2)
    return pred


print(vec2scalar(predictions))

[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 1, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 1, 1, 1, 1, 1, 1, 2, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 2, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]


In [22]:
print(vec2scalar(predictions))

[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 1, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 1, 1, 1, 1, 1, 1, 2, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 2, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]


In [23]:
_, accuracy = model.evaluate(x, encoded_Y)
print(f"Accuracy: {accuracy * 100:.2f}%")

6/6 [==============================] - 0s 2ms/step - loss: 0.3268 - accuracy: 0.8820
Accuracy: 88.20%
