# Multiclass Classification

In [1]:
import pandas as pd
from keras.models import Sequential# supervised
from keras.layers import Dense
from sklearn.datasets import load_iris
import numpy as np

In [2]:
data = load_iris()

In [3]:
df = pd.DataFrame(data.data,columns = data.feature_names)
df2 = pd.DataFrame(data.target,columns = ['Target'])

In [4]:
df2.head()

Target
0       0
1       0
2       0
3       0
4       0

In [5]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [6]:
from keras.utils import np_utils
encoded_Y=np_utils.to_categorical(df2)
encoded_Y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [7]:
model=Sequential()
model.add(Dense(8,input_dim=4,activation='relu')) 
model.add(Dense(6,activation='relu'))
model.add(Dense(3,activation='softmax'))

In [8]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics='accuracy') 

In [9]:
model.fit(df,encoded_Y,epochs=100,batch_size=10)

Epoch 1/100
15/15 [==============================] - 0s 1ms/step - loss: 2.5270 - accuracy: 0.3333
Epoch 2/100
15/15 [==============================] - 0s 840us/step - loss: 2.1773 - accuracy: 0.3333
Epoch 3/100
15/15 [==============================] - 0s 820us/step - loss: 1.8935 - accuracy: 0.3333
Epoch 4/100
15/15 [==============================] - 0s 903us/step - loss: 1.6952 - accuracy: 0.3333
Epoch 5/100
15/15 [==============================] - 0s 881us/step - loss: 1.5275 - accuracy: 0.3333
Epoch 6/100
15/15 [==============================] - 0s 1ms/step - loss: 1.4162 - accuracy: 0.3333
Epoch 7/100
15/15 [==============================] - 0s 875us/step - loss: 1.3218 - accuracy: 0.3333
Epoch 8/100
15/15 [==============================] - 0s 835us/step - loss: 1.2538 - accuracy: 0.3333
Epoch 9/100
15/15 [==============================] - 0s 824us/step - loss: 1.2004 - accuracy: 0.3333
Epoch 10/100
15/15 [==============================] - 0s 780us/step - loss: 1.1577 - accuracy: 

15/15 [==============================] - 0s 764us/step - loss: 0.5816 - accuracy: 0.7600
Epoch 82/100
15/15 [==============================] - 0s 749us/step - loss: 0.5776 - accuracy: 0.7800
Epoch 83/100
15/15 [==============================] - 0s 734us/step - loss: 0.5739 - accuracy: 0.7800
Epoch 84/100
15/15 [==============================] - 0s 830us/step - loss: 0.5709 - accuracy: 0.8200
Epoch 85/100
15/15 [==============================] - 0s 808us/step - loss: 0.5670 - accuracy: 0.8000
Epoch 86/100
15/15 [==============================] - 0s 745us/step - loss: 0.5634 - accuracy: 0.7867
Epoch 87/100
15/15 [==============================] - 0s 742us/step - loss: 0.5608 - accuracy: 0.7867
Epoch 88/100
15/15 [==============================] - 0s 796us/step - loss: 0.5562 - accuracy: 0.8000
Epoch 89/100
15/15 [==============================] - 0s 730us/step - loss: 0.5532 - accuracy: 0.8200
Epoch 90/100
15/15 [==============================] - 0s 775us/step - loss: 0.5493 - accuracy: 

In [10]:
predictions=model.predict(df)

5/5 [==============================] - 0s 1ms/step


In [11]:
predictions

array([[6.6144305e-01, 2.2258976e-01, 1.1596722e-01],
       [6.6144305e-01, 2.2258976e-01, 1.1596722e-01],
       [6.6144305e-01, 2.2258976e-01, 1.1596722e-01],
       [6.6144305e-01, 2.2258976e-01, 1.1596722e-01],
       [6.6144305e-01, 2.2258976e-01, 1.1596722e-01],
       [6.6144305e-01, 2.2258976e-01, 1.1596722e-01],
       [6.6144305e-01, 2.2258976e-01, 1.1596722e-01],
       [6.6144305e-01, 2.2258976e-01, 1.1596722e-01],
       [6.6144305e-01, 2.2258976e-01, 1.1596722e-01],
       [6.6144305e-01, 2.2258976e-01, 1.1596722e-01],
       [6.6144305e-01, 2.2258976e-01, 1.1596722e-01],
       [6.6144305e-01, 2.2258976e-01, 1.1596722e-01],
       [6.6144305e-01, 2.2258976e-01, 1.1596722e-01],
       [6.6144305e-01, 2.2258976e-01, 1.1596722e-01],
       [6.6144305e-01, 2.2258976e-01, 1.1596722e-01],
       [6.6144305e-01, 2.2258976e-01, 1.1596722e-01],
       [6.6144305e-01, 2.2258976e-01, 1.1596722e-01],
       [6.6144305e-01, 2.2258976e-01, 1.1596722e-01],
       [6.6144305e-01, 2.225

In [12]:
for i in range(35,130,3):
    print(predictions[i],encoded_Y[i])

[0.66144305 0.22258976 0.11596722] [1. 0. 0.]
[0.66144305 0.22258976 0.11596722] [1. 0. 0.]
[0.66144305 0.22258976 0.11596722] [1. 0. 0.]
[0.66144305 0.22258976 0.11596722] [1. 0. 0.]
[0.66144305 0.22258976 0.11596722] [1. 0. 0.]
[0.00871958 0.4819574  0.50932306] [0. 1. 0.]
[0.0165642  0.50616825 0.47726747] [0. 1. 0.]
[0.01011931 0.48274568 0.50713503] [0. 1. 0.]
[0.02778124 0.53013843 0.4420804 ] [0. 1. 0.]
[0.01904456 0.5245977  0.45635775] [0. 1. 0.]
[0.01207644 0.49646115 0.4914624 ] [0. 1. 0.]
[0.00442164 0.42891872 0.5666597 ] [0. 1. 0.]
[0.02058868 0.5220568  0.45735458] [0. 1. 0.]
[0.01493068 0.5090212  0.47604805] [0. 1. 0.]
[0.0036378  0.42130494 0.57505727] [0. 1. 0.]
[0.03128775 0.54192257 0.42678967] [0. 1. 0.]
[0.00423518 0.431444   0.56432086] [0. 1. 0.]
[0.00771242 0.4700515  0.52223605] [0. 1. 0.]
[0.02064725 0.5191465  0.4602062 ] [0. 1. 0.]
[0.02323973 0.52992904 0.44683126] [0. 1. 0.]
[0.03222843 0.5424513  0.4253202 ] [0. 1. 0.]
[0.08681483 0.54787904 0.36530608]

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df,encoded_Y,random_state=1,test_size=0.25)

In [14]:
y_train.shape

(112, 3)

In [15]:
y_test.shape

(38, 3)

In [16]:
model=Sequential()
model.add(Dense(68,input_dim=4,activation='relu'))
model.add(Dense(6,activation='relu'))
model.add(Dense(3,activation='softmax'))

In [17]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics='accuracy')

In [18]:
model.fit(x_train,y_train,epochs=100,batch_size=10)

Epoch 1/100
12/12 [==============================] - 0s 1ms/step - loss: 1.5618 - accuracy: 0.3304
Epoch 2/100
12/12 [==============================] - 0s 958us/step - loss: 1.1595 - accuracy: 0.3929
Epoch 3/100
12/12 [==============================] - 0s 976us/step - loss: 1.0572 - accuracy: 0.5268
Epoch 4/100
12/12 [==============================] - 0s 922us/step - loss: 1.0417 - accuracy: 0.4821
Epoch 5/100
12/12 [==============================] - 0s 833us/step - loss: 1.0264 - accuracy: 0.5357
Epoch 6/100
12/12 [==============================] - 0s 893us/step - loss: 1.0095 - accuracy: 0.5625
Epoch 7/100
12/12 [==============================] - 0s 982us/step - loss: 0.9944 - accuracy: 0.5446
Epoch 8/100
12/12 [==============================] - 0s 920us/step - loss: 0.9792 - accuracy: 0.5804
Epoch 9/100
12/12 [==============================] - 0s 762us/step - loss: 0.9621 - accuracy: 0.5536
Epoch 10/100
12/12 [==============================] - 0s 987us/step - loss: 0.9491 - accuracy

12/12 [==============================] - 0s 800us/step - loss: 0.5758 - accuracy: 0.6964
Epoch 82/100
12/12 [==============================] - 0s 780us/step - loss: 0.5729 - accuracy: 0.6964
Epoch 83/100
12/12 [==============================] - 0s 791us/step - loss: 0.5712 - accuracy: 0.6964
Epoch 84/100
12/12 [==============================] - 0s 832us/step - loss: 0.5694 - accuracy: 0.6964
Epoch 85/100
12/12 [==============================] - 0s 803us/step - loss: 0.5673 - accuracy: 0.7054
Epoch 86/100
12/12 [==============================] - 0s 868us/step - loss: 0.5611 - accuracy: 0.8036
Epoch 87/100
12/12 [==============================] - 0s 842us/step - loss: 0.5645 - accuracy: 0.7679
Epoch 88/100
12/12 [==============================] - 0s 925us/step - loss: 0.5637 - accuracy: 0.6964
Epoch 89/100
12/12 [==============================] - 0s 884us/step - loss: 0.5578 - accuracy: 0.7589
Epoch 90/100
12/12 [==============================] - 0s 780us/step - loss: 0.5418 - accuracy: 

In [19]:
y_pred = model.predict(x_test)

y_pred

#y_pred = model2.predict(x_test)

2/2 [==============================] - 0s 2ms/step


array([[9.9993503e-01, 6.4627733e-05, 3.6364719e-07],
       [1.6004464e-01, 7.8079242e-01, 5.9162956e-02],
       [1.3615496e-01, 7.7635324e-01, 8.7491781e-02],
       [9.9978381e-01, 2.1429990e-04, 1.9000697e-06],
       [1.4012814e-01, 5.2138126e-01, 3.3849061e-01],
       [1.4553262e-01, 6.8468523e-01, 1.6978212e-01],
       [1.2774508e-01, 4.2028230e-01, 4.5197260e-01],
       [9.9868578e-01, 1.2923528e-03, 2.1877851e-05],
       [9.9787509e-01, 2.0831316e-03, 4.1769548e-05],
       [1.2242901e-01, 3.8693529e-01, 4.9063566e-01],
       [1.4616328e-01, 6.6176212e-01, 1.9207458e-01],
       [9.9945098e-01, 5.4298877e-04, 6.0960965e-06],
       [1.2242901e-01, 3.8693529e-01, 4.9063566e-01],
       [1.4093088e-01, 7.4411720e-01, 1.1495192e-01],
       [1.4626414e-01, 6.3840711e-01, 2.1532878e-01],
       [9.9877113e-01, 1.2034583e-03, 2.5399326e-05],
       [1.4157476e-01, 7.3853666e-01, 1.1988862e-01],
       [1.4471285e-01, 5.8496428e-01, 2.7032277e-01],
       [9.9872512e-01, 1.259

In [20]:
def vec2scalar(list_):
    pred = []
    for i in list_:
        val = [round(j,0) for j in i]
        if val[0]==1.0:
            pred.append(0)
        elif val[1]==1.0:
            pred.append(1)
        else:
            pred.append(2)
    return pred

In [21]:
print(vec2scalar(y_pred))

[0, 1, 1, 0, 1, 1, 2, 0, 0, 2, 1, 0, 2, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 2, 1, 0, 0, 1, 2, 1, 2, 1, 2, 2, 0, 1, 0]


In [22]:
print(vec2scalar(y_test))

[0, 1, 1, 0, 2, 1, 2, 0, 0, 2, 1, 0, 2, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 2, 1, 0, 0, 1, 2, 1, 2, 1, 2, 2, 0, 1, 0]
