In [8]:
from keras.datasets import cifar10

# importing images with different variations

In [2]:
from keras.layers import Conv2D,Activation,Dropout,MaxPooling2D,Flatten,Dense

# Dropout = To drop unused neurons
# Activation = to define Activation func


In [3]:
import numpy as np

In [4]:
import matplotlib.pyplot as plt

In [9]:
(X_train, y_train),(X_test, y_test) = cifar10.load_data()

170498071/170498071 [==============================] - 161s 1us/step


In [10]:
X_train.shape

(50000, 32, 32, 3)

In [11]:
X_test.shape

(10000, 32, 32, 3)

**Reducing Pixel size to decimal**

In [15]:
X_train = X_train.astype('float32')

X_test = X_test.astype('float32')

# converting pixels into float

In [16]:
X_train /= 255

# dividing pixel by total pixel size

In [17]:
X_test /= 255

**Building the Model**

In [18]:
from keras.models import Sequential

In [19]:
model = Sequential()

**Layer 1**

In [20]:
model.add(Conv2D(32, (3,3), padding='same', input_shape = X_train.shape[1:]))

In [21]:
# Adding activation function seperately.

model.add(Activation('relu'))

**Layer 2**

In [22]:
model.add(Conv2D(32, (3,3)))

In [23]:
model.add(Activation('relu'))

In [24]:
model.add(MaxPooling2D(pool_size=(2,2)))

# adding MaxPooling to remove less important features.

In [25]:
model.add(Dropout(0.25))

# droping 25% less important Neurons

In [26]:
model.add(Flatten())

**Hidden Layer**

In [27]:
model.add(Dense(512))

In [28]:
model.add(Activation('relu'))

In [29]:
model.add(Dropout(0.5))

**Output Layer**

In [30]:
model.add(Dense(10))

In [31]:
model.add(Activation('softmax'))

**Compile the model**

In [32]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics='accuracy')

In [33]:
from keras.utils import to_categorical

In [34]:
y_train = to_categorical(y_train, 10)

In [35]:
y_train[0]

array([0., 0., 0., 0., 0., 0., 1., 0., 0., 0.], dtype=float32)

In [36]:
y_test = to_categorical(y_test, 10)

In [37]:
y_test[0]

array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [40]:
model.fit(X_train, y_train, validation_data=(X_test, y_test), batch_size = 32, epochs =5)

Epoch 1/5
1563/1563 [==============================] - 73s 47ms/step - loss: 1.7584 - accuracy: 0.3750 - val_loss: 326.9555 - val_accuracy: 0.1319
Epoch 2/5
1563/1563 [==============================] - 73s 47ms/step - loss: 1.7265 - accuracy: 0.3896 - val_loss: 307.8936 - val_accuracy: 0.1301
Epoch 3/5
1563/1563 [==============================] - 74s 47ms/step - loss: 1.6903 - accuracy: 0.4008 - val_loss: 206.2339 - val_accuracy: 0.1429
Epoch 4/5
1563/1563 [==============================] - 75s 48ms/step - loss: 1.6439 - accuracy: 0.4173 - val_loss: 149.7285 - val_accuracy: 0.1839
Epoch 5/5
1563/1563 [==============================] - 74s 47ms/step - loss: 1.6024 - accuracy: 0.4312 - val_loss: 218.4624 - val_accuracy: 0.1832


In [41]:
predictions = model.predict(X_test)

for i in range(5):
    print(y_test[i])
    print(predictions[i])
    

313/313 [==============================] - 5s 17ms/step
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[3.3234006e-23 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
 0.0000000e+00 0.0000000e+00 0.0000000e+00 1.0000000e+00 0.0000000e+00]
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
[1.0000000e+00 0.0000000e+00 0.0000000e+00 3.0580526e-31 0.0000000e+00
 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00]
